name: Build and Release

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
          
      - name: Create distribution directory
        run: mkdir -p dist
          
      - name: Build for Linux (amd64)
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o dist/git-rm-merged-linux-amd64
          
      - name: Build for Linux (arm64)
        env:
          GOOS: linux
          GOARCH: arm64
        run: go build -o dist/git-rm-merged-linux-arm64
          
      - name: Build for macOS (amd64)
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -o dist/git-rm-merged-darwin-amd64
          
      - name: Build for macOS (arm64)
        env:
          GOOS: darwin
          GOARCH: arm64
        run: go build -o dist/git-rm-merged-darwin-arm64
          
      - name: Build for Windows (amd64)
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -o dist/git-rm-merged-windows-amd64.exe
          
      - name: Build for Windows (arm64)
        env:
          GOOS: windows
          GOARCH: arm64
        run: go build -o dist/git-rm-merged-windows-arm64.exe

      - name: Get the Tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release on Tag
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            dist/git-rm-merged-linux-amd64
            dist/git-rm-merged-linux-arm64
            dist/git-rm-merged-darwin-amd64
            dist/git-rm-merged-darwin-arm64
            dist/git-rm-merged-windows-amd64.exe
            dist/git-rm-merged-windows-arm64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
